name: jira-cli
base: core20
version: git
summary: Command line interface to Atlassian's JIRA.
description: |
  Ankit Pokhrel's command line interface to Atlassian's JIRA product.
grade: stable
license: MIT
issues: https://github.com/davel/jira-cli-snap/issues
source-code: https://github.com/davel/jira-cli-snap
website: https://github.com/ankitpokhrel/jira-cli

confinement: strict

apps:
  jira-cli:
    command: bin/jira
    plugs:
      - home
      - network

parts:
  jira-cli:
    plugin: go
    source-type: git
    source: https://github.com/ankitpokhrel/jira-cli
    source-tag: v1.3.0
