name: jira-cli
base: core20
version: git
summary: Command line interface to Atlassian's JIRA.
description: |
  Ankit Pokhrel's command line interface to Atlassian's JIRA product.
grade: stable
license: MIT

confinement: strict

apps:
  jira-cli:
    command: bin/jira
    plugs:
      - home

parts:
  jira-cli:
    plugin: go
    source-type: git
    source: https://github.com/ankitpokhrel/jira-cli
